### PR TITLE
docs: fix the 404 link

### PR DESCRIPTION
**Pull request by cqqqq777**
#### What type of PR is this?

docs

#### What this PR does / why we need it (en: English/zh: Chinese):

en: fix the 404 link
zh:

### CODE REVIEW

**Comment by welkeyever** [comment]
LGTM, thx~

**Comment by li-jin-gou** [comment]
http3 docs is https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/protocol/http3/ @cqqqq777

**Comment by cqqqq777** [comment]
sorry

**Comment by cqqqq777** [comment]
#7

**Pull request merged**
